HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = orbitSim

HD_LIBRARY_SRC_cxx      = GLAST_slew_estimate.cxx \
                          OrbSim.cxx \
                          atFunctions.cxx \
                          functUtil.cxx \
                          read_ephem.cxx

HD_SUBDIRS              = orbSim

HD_CXXFLAGS             = -std=c++11 ${HD_STD_CXXFLAGS} -L/Users/jasercio/boost_1_65_1/stage/lib -I/Users/jasercio/boost_1_65_1

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
